name: CI-iOS

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-13
    
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.3.app
    
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Build and test
      run: xcodebuild clean build test -workspace SolanaSwiftSDK/MySolWallet/MySolWallet.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="Apple Development: Deniz Tutuncu (VVBFBA275T)" CODE_SIGNING_REQUIRED=YES -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.4" ONLY_ACTIVE_ARCH=YES
