name: CI-iOS

on:
    pull_request:
    branches: [ "main" ]

jobs:
    build-and-test:
    runs-on: macos-latest
    
    timeout-minutes: 20
    
    steps:
    - name: Checkout code
        uses: actions/checkout@v2
    
    - name: Select up Xcode
        run: sudo xcode-select -s /Applications/Xcode_14.3.app
    
    - name: Show Xcode version
        run: xcodebuild -version
    
    - name: Install keychain
        run: |
        security create-keychain -p mysecretpassword github-actions.keychain
        security default-keychain -d user -s github-actions.keychain
        security unlock-keychain -p ${{ secrets.P12_PASSWORD }} github-actions.keychain
        security set-keychain-settings -t 3600 -u github-actions.keychain
    
    - name: Add keychain to keychain list
        run: security list-keychains -s github-actions.keychain
    
    - name: Import certificate to keychain
        run: |
            security import /Users/deniztutuncu/Desktop/Certificates/SolanaPackage/SolanaPackageCertificates.p12 -k github-actions.keychain -P ${{ secrets.P12_PASSWORD }} -T /usr/bin/codesign
    
    - name: Build and test with keychain
        run: |
        xcodebuild clean build test \
            -workspace SolanaSwiftSDK/MySolWallet/MySolWallet.xcworkspace \
            -scheme "CI_iOS" \
            -sdk iphonesimulator \
            -destination "platform=iOS Simulator,name=iPhone 14 Pro Max,OS=16.4" \
            ONLY_ACTIVE_ARCH=YES \
            CODE_SIGN_IDENTITY="Apple Development: Deniz Tutuncu (VVBFBA275T)" \
            CODE_SIGNING_REQUIRED=YES \
            CODE_SIGN_KEYCHAIN="github-actions.keychain"
    
    - name: Remove keychain
        run: |
        security delete-keychain github-actions.keychain

