name: CI-iOS

on:
    push:
        branches: [ "development" ]
    pull_request:
        branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest
    
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.2.app
    
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
      
    - name: Build and test
      run: xcodebuild clean build test -workspace SolanaSwiftSDK/MySolWallet/MySolWallet.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro" ONLY_ACTIVE_ARCH=YES

