name: CI-macOS

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: macos-13
    
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.3.app
    
    - name: Xcode version
    run: /usr/bin/xcodebuild -version
      
    - name: Build and test
      run: xcodebuild clean build test -project SolanaSwiftSDK/SolanaPackage/SolanaPackage.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
    
