name: CI-macOS

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-13
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install provisioning profile
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.PROVISIONING_PROFILE }}" --output .github/deployment/SolanaKeychainMacOSAppDev.provisionprofile .github/deployment/SolanaKeychainMacOSAppDev.provisionprofile.gpg
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp .github/deployment/SolanaKeychainMacOSAppDev.provisionprofile ~/Library/MobileDevice/Provisioning\ Profiles/
          
      - name: Install keychain certificate
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.MACDEVELOPERID_CERTIFICATEGPG }}" --output .github/deployment/AppleDeveloperIDApplicationCertificate.p12 .github/deployment/AppleDeveloperIDApplicationCertificate.p12.gpg
          security create-keychain -p "" build.keychain
          security import .github/deployment/AppleDeveloperIDApplicationCertificate.p12 -t agg -k ~/Library/Keychains/build.keychain -P "${{ secrets.MACDEVELOPERID_CERTIFICATE }}" -A
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain
        
      - name: Select up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Show Xcode version
        run: xcodebuild -version
        
      - name: Build and test with keychain
        run: |
          xcodebuild clean build test \
            -project SolanaSwiftSDK/SolanaPackage/SolanaPackage.xcodeproj \
            -scheme "CI_macOS" \
            -allowProvisioningUpdates \
            -sdk macosx \
            -destination "platform=macOS" \
            ONLY_ACTIVE_ARCH=YES \
            CODE_SIGN_IDENTITY="Developer ID Application: Deniz Tutuncu (9DGMQB3935)" \
            CODE_SIGNING_REQUIRED=YES \
            CODE_SIGN_KEYCHAIN="build.keychain"
            
      - name: Remove keychain
        run: |
          security delete-keychain build.keychain
