name: CI

on:
    push:
        branches: [ "development" ]
    pull_request:
        branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.2.app
    
    - name: Build and test MacOS
      run: xcodebuild clean build test -project SolanaSwiftSDK/SolanaPackage/SolanaPackage.xcodeproj -scheme "CI_macOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
      
    - name: Build and test iOS
      run: xcodebuild clean build test -workspace SolanaSwiftSDK/MySolWallet/MySolWallet.xcworkspace -scheme "CI_iOS" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk iphonesimulator -destination "platform=iOS Simulator,OS=15.0,name=iPhone 14 Pro" ONLY_ACTIVE_ARCH=YES

