name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: macos-13

    steps:
      - uses: actions/checkout@v2

      - name: Install provisioning profile
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.PROVISIONING_PROFILE }}" --output .github/deployment/MySolWalletApp.mobileprovision .github/deployment/MySolWalletApp.mobileprovision.gpg
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp .github/deployment/MySolWalletApp.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Install keychain certificate
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.DISTRIBUTION_CERTIFICATE }}" --output .github/deployment/AppleDistributionCertificate.p12 .github/deployment/AppleDistributionCertificate.p12.gpg
          security create-keychain -p "" build.keychain
          security import .github/deployment/AppleDistributionCertificate.p12 -t agg -k ~/Library/Keychains/build.keychain -P "${{ secrets.KEYCHAIN_PASSWORD }}" -A
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "" ~/Library/Keychains/build.keychain

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.2.app
      
      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Set build number
        run: |
          buildNumber=$(($GITHUB_RUN_NUMBER + 1))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "SolanaSwiftSDK/MySolWallet/MySolWallet/Info.plist"

      - name: Build
        run: xcodebuild clean archive -sdk iphoneos -workspace SolanaSwiftSDK/MySolWallet/MySolWallet.xcworkspace -configuration "Release" -scheme "MySolWallet" -derivedDataPath "DerivedData" -archivePath "DerivedData/Archive/MySolWallet.xcarchive"
    
      - name: Export
        run: xcodebuild -exportArchive -archivePath DerivedData/Archive/MySolWallet.xcarchive -exportOptionsPlist .github/deployment/ExportOptions.plist -exportPath DerivedData/ipa
      
      - name: Deploy
        run: xcrun altool --upload-app --type ios --file "DerivedData/ipa/MySolWallet.ipa" --username "${{ secrets.APPSTORE_USERNAME }}" --password "${{ secrets.APPSTORE_PASSWORD }}" --verbose

